# Production override for docker-compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: "3.8"

services:
  postgres:
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    # Remove port exposure for security in production
    ports: []

  api:
    restart: always
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - jwt_secret
    # Only expose necessary ports
    ports:
      - "3000:3000"

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
