# Render Blueprint for SprintSync Backend
# This file defines the infrastructure for deploying on Render

services:
  # Main API Service
  - type: web
    name: sprintsync-api
    runtime: docker
    repo: https://github.com/Payne680/sprintsync-backend.git
    branch: main
    dockerfilePath: ./Dockerfile
    numInstances: 1
    plan: starter # Change to 'standard' or higher for production
    buildCommand: "" # Render handles Docker build
    startCommand: "" # Uses CMD from Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: sprintsync-api
          property: port
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure random value
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        fromDatabase:
          name: sprintsync-db
          property: connectionString
# Optional: Redis for caching (comment out if not needed initially)
# - type: redis
#   name: sprintsync-redis
#   plan: free
#   maxmemoryPolicy: allkeys-lru
