name: Security Scan (Weekly)

on:
  schedule:
    - cron: "0 2 * * 1" # Weekly on Monday at 2 AM
  workflow_dispatch:

jobs:
  security-scan:
    name: Basic Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate

      - name: Check for common security issues
        run: |
          echo "🔍 Running basic security checks..."

          # Check for hardcoded secrets (excluding test files)
          echo "Checking for hardcoded secrets..."
          if grep -r -i "password\|secret\|key\|token" src/ --exclude-dir=tests --exclude="*.test.js" | grep -v "JWT_SECRET\|DATABASE_URL\|NODE_ENV"; then
            echo "⚠️  Potential hardcoded secrets found"
          else
            echo "✅ No hardcoded secrets detected"
          fi

          # Check for console.log statements (should be removed in production)
          echo "Checking for console.log statements..."
          if grep -r "console.log" src/ --exclude-dir=tests --exclude="*.test.js"; then
            echo "⚠️  console.log statements found - consider removing for production"
          else
            echo "✅ No console.log statements found"
          fi

          echo "✅ Basic security scan completed"
